from django.urls import path
from management.api.v1 import views

urlpatterns = [
    path("public/<str:tenant_id>", views.public_tenant),
    path("public/<str:tenant_id>/pay", views.public_pay),
    path("public/<str:tenant_id>/verify", views.public_verify),
    path("dashboard/stats", views.dashboard_stats),
    path("customers", views.customers),
    path("customers/add", views.customer_add),
    path("customers/<str:customer_id>", views.customers),
    path("customers/<str:customer_id>/renew", views.customer_renew),
    path("payments", views.payments),
    path("invoices", views.invoices),
    path("invoices/<str:invoice_id>", views.invoices),
    path("payments/pay", views.payments),
    path("payments/<str:payment_id>/mark-paid", views.payment_mark_paid),
    path("reports/revenue", views.report_revenue),
    path("reports/customers", views.report_customers),
    path("reports/packages", views.report_packages),
    path("reports/expenses", views.report_expenses),
    path("profile", views.profile),
    path("settings/business", views.settings_business),
    path("settings/logo", views.settings_logo),
    path("settings/test-sms", views.settings_test_sms),
    path("settings/test-whatsapp", views.settings_test_whatsapp),
    path("settings/expiry-notifications", views.send_expiry_notifications),
    path("settings/delete-customers", views.settings_delete_customers),
    path("settings/notifications", views.settings_notifications),
    path("staff", views.staff_members),
    path("staff/profile", views.staff_profile),
    path("staff/tasks", views.staff_tasks),
    path("staff/tasks/<str:ticket_id>", views.staff_tasks),
    path("staff/reports", views.staff_reports),
    path("staff/requisitions", views.staff_requisitions),
    path("team/members", views.team_members),
    path("team/invite", views.team_invite),
    path("team/members/<str:member_id>", views.team_members),
    path("team/members/<str:member_id>/permissions", views.team_member_permissions),
    path("tickets", views.tickets),
    path("tickets/add", views.tickets),
    path("tickets/<str:ticket_id>", views.tickets),
    path("daraja/callback/<str:tenant_id>/<str:payment_id>/<str:token>", views.daraja_callback),
]
