from django.conf import settings
from django.urls import include, path

from core.api.v1 import views as core_views
from management.api.v1 import views as management_views
from network.api.v1 import views as network_views


admin_urlpatterns = [
    path("auth/login", core_views.admin_login),
    path("tenants", core_views.admin_tenants),
    path("tenants/", core_views.admin_tenants),
    path("tenants/stats/summary", core_views.admin_stats),
    path("system/stats", core_views.admin_system_stats),
    path("system", core_views.admin_system),
    path("system/migrations", core_views.admin_system_migrations),
    path("subscriptions", core_views.admin_subscriptions),
    path("subscriptions/revenue-chart", core_views.admin_revenue_chart),
    path("subscriptions/<int:subscription_id>", core_views.admin_subscriptions),
    path("subscriptions/<int:subscription_id>/payments", core_views.admin_subscription_payments),
    path("tenants/<str:tenant_id>/subscription", core_views.admin_tenant_subscription),
    path("tenants/<str:tenant_id>/subscription/remind", core_views.admin_subscription_remind),
    path("tenants/<str:tenant_id>/mikrotik/test", core_views.admin_mikrotik_test),
    path("tenants/audit/logs", core_views.admin_audit_logs),
    path("tenants/<str:tenant_id>", core_views.admin_tenants),
    path("tenants/<str:tenant_id>/<str:child>", core_views.admin_tenants),
    path("site", core_views.admin_site),
    path("site/", core_views.admin_site),
    path("users", core_views.admin_users),
    path("users/", core_views.admin_users),
    path("users/<str:tenant_id>/<str:customer_id>", core_views.admin_users),
    path("users/<str:tenant_id>/<str:customer_id>/<str:action>", core_views.admin_users),
]

urlpatterns = [
    path("health", core_views.health),
    path("health/", core_views.health),
    path("generate_204", network_views.captive_probe),
    path("hotspot-detect.html", network_views.captive_probe),
    path("connecttest.txt", network_views.captive_probe),
    path("ncsi.txt", network_views.captive_probe),
    path("auth/register", core_views.auth_register),
    path("auth/login", core_views.auth_login),
    path("public/site", core_views.public_site),
    path("public/stats", core_views.public_stats),
    path("public/<str:tenant_id>", management_views.public_tenant),
    path("public/<str:tenant_id>/packages", network_views.public_packages),
    path("public/<str:tenant_id>/pppoe-profile", network_views.public_pppoe_profile),
    path("public/<str:tenant_id>/pay", management_views.public_pay),
    path("public/<str:tenant_id>/redeem", network_views.public_redeem),
    path("public/<str:tenant_id>/voucher-login", network_views.public_voucher_login),
    path("public/<str:tenant_id>/verify", management_views.public_verify),
    path("captive/<str:tenant_id>", network_views.captive_portal_page),
    path("captive/<str:tenant_id>/hotspot-file/<str:page>", network_views.captive_hotspot_file),
    path("captive/<str:tenant_id>/pay", network_views.captive_portal_pay),
    path("dashboard/stats", management_views.dashboard_stats),
    path("customers", management_views.customers),
    path("customers/", management_views.customers),
    path("customers/add", management_views.customer_add),
    path("customers/hotspot-portal", network_views.customer_hotspot_portal),
    path("customers/<str:customer_id>", management_views.customers),
    path("customers/<str:customer_id>/provision", network_views.customer_provision),
    path("customers/<str:customer_id>/renew", management_views.customer_renew),
    path("packages", network_views.packages),
    path("packages/", network_views.packages),
    path("packages/add", network_views.package_add),
    path("packages/router/profiles", network_views.router_profiles),
    path("router/status", network_views.router_status),
    path("router/ports", network_views.router_ports),
    path("router/suspend", network_views.router_suspend),
    path("router/delete", network_views.router_delete),
    path("router/reboot", network_views.router_reboot),
    path("router/resources", network_views.router_resources),
    path("router/provision-command", network_views.router_provision_command),
    path("router/provision/<str:token>", network_views.router_provision_script),
    path("router/provision/<str:token>/complete", network_views.router_provision_complete),
    path("router/provision/<str:token>/snapshot/<str:section>", network_views.router_provision_snapshot),
    path("router/agent/<str:token>/poll", network_views.router_agent_poll),
    path("router/agent/<str:token>/ack/<str:command_id>", network_views.router_agent_ack),
    path("packages/sync-all", network_views.package_sync),
    path("packages/<str:package_id>", network_views.packages),
    path("packages/<str:package_id>/sync", network_views.package_sync),
    path("payments", management_views.payments),
    path("vouchers", network_views.vouchers),
    path("vouchers/<str:voucher_id>", network_views.vouchers),
    path("payments/", management_views.payments),
    path("payments/pay", management_views.payments),
    path("payments/<str:payment_id>/mark-paid", management_views.payment_mark_paid),
    path("reports/revenue", management_views.report_revenue),
    path("reports/customers", management_views.report_customers),
    path("reports/packages", management_views.report_packages),
    path("reports/expenses", management_views.report_expenses),
    path("subscription/status", core_views.tenant_subscription_status),
    path("profile", management_views.profile),
    path("settings/business", management_views.settings_business),
    path("settings/logo", management_views.settings_logo),
    path("settings/test-sms", management_views.settings_test_sms),
    path("settings/test-whatsapp", management_views.settings_test_whatsapp),
    path("settings/expiry-notifications", management_views.send_expiry_notifications),
    path("settings/delete-customers", management_views.settings_delete_customers),
    path("settings/mikrotik", network_views.settings_mikrotik),
    path("settings/mikrotik/test", network_views.settings_mikrotik_test),
    path("settings/notifications", management_views.settings_notifications),
    path("staff", management_views.staff_members),
    path("team/members", management_views.team_members),
    path("team/members/", management_views.team_members),
    path("team/invite", management_views.team_invite),
    path("team/members/<str:member_id>", management_views.team_members),
    path("team/members/<str:member_id>/permissions", management_views.team_member_permissions),
    path("requisitions", management_views.requisitions),
    path("requisitions/<str:requisition_id>", management_views.requisitions),
    path("staff/tasks", management_views.staff_tasks),
    path("staff/tasks/<str:ticket_id>", management_views.staff_tasks),
    path("staff/profile", management_views.staff_profile),
    path("staff/reports", management_views.staff_reports),
    path("staff/requisitions", management_views.staff_requisitions),
    path("tickets", management_views.tickets),
    path("tickets/add", management_views.tickets),
    path("tickets/<str:ticket_id>", management_views.tickets),
    path("daraja/callback/<str:tenant_id>/<str:payment_id>/<str:token>", management_views.daraja_callback),
    path("daraja/b2c/result", management_views.daraja_b2c_result),
    path("daraja/b2c/timeout", management_views.daraja_b2c_timeout),
    path(f"{settings.ADMIN_API_PATH}/", include(admin_urlpatterns)),
]
