from django.urls import path
from network.api.v1 import views

urlpatterns = [
    path("public/<str:tenant_id>/packages", views.public_packages),
    path("public/<str:tenant_id>/pppoe-profile", views.public_pppoe_profile),
    path("public/<str:tenant_id>/redeem", views.public_redeem),
    path("public/<str:tenant_id>/voucher-login", views.public_voucher_login),
    path("captive/<str:tenant_id>", views.captive_portal_page),
    path("captive/<str:tenant_id>/hotspot-file/<str:page>", views.captive_hotspot_file),
    path("captive/<str:tenant_id>/pay", views.captive_portal_pay),
    path("customers/<str:customer_id>/provision", views.customer_provision),
    path("packages", views.packages),
    path("packages/add", views.package_add),
    path("packages/router/profiles", views.router_profiles),
    path("packages/sync-all", views.package_sync),
    path("packages/<str:package_id>", views.packages),
    path("packages/<str:package_id>/sync", views.package_sync),
    path("vouchers", views.vouchers),
    path("vouchers/<str:voucher_id>", views.vouchers),
    path("router/status", views.router_status),
    path("router/ports", views.router_ports),
    path("router/suspend", views.router_suspend),
    path("router/delete", views.router_delete),
    path("router/reboot", views.router_reboot),
    path("router/resources", views.router_resources),
    path("router/provision-command", views.router_provision_command),
    path("router/provision/<str:token>", views.router_provision_script),
    path("router/provision/<str:token>/complete", views.router_provision_complete),
    path("router/provision/<str:token>/snapshot/<str:section>", views.router_provision_snapshot),
    path("router/agent/<str:token>/poll", views.router_agent_poll),
    path("router/agent/<str:token>/ack/<str:command_id>", views.router_agent_ack),
    path("settings/mikrotik", views.settings_mikrotik),
    path("settings/mikrotik/test", views.settings_mikrotik_test),
]
