# Generated by Django 6.0.5 on 2026-07-26 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_api', '0012_radius_aaa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=80)),
                ('password', models.CharField(blank=True, default='', max_length=80)),
                ('package', models.CharField(blank=True, default='', max_length=255)),
                ('package_id', models.CharField(blank=True, default='', max_length=80)),
                ('price', models.FloatField(default=0)),
                ('status', models.CharField(default='active', max_length=40)),
                ('service_type', models.CharField(default='hotspot', max_length=30)),
                ('router_status', models.CharField(default='pending', max_length=40)),
                ('router_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='radiusnasclient',
            name='unique_nas_client_per_tenant',
        ),
        migrations.AlterUniqueTogether(
            name='radiusnasclient',
            unique_together={('tenant', 'nas_ip')},
        ),
        migrations.AddField(
            model_name='voucher',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='billing_api.tenant'),
        ),
    ]
