# Generated by Django 6.0.5 on 2026-08-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_api', '0013_voucher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paystack_access_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paystack_authorization_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paystack_authorization_url',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paystack_channel',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paystack_customer_email',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paystack_paid_at',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paystack_reference',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paystack_transaction_id',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='paystack_bearer',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='paystack_currency',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='paystack_secret_key',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='paystack_subaccount_code',
        ),
    ]
